<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="src/DurableTask.Core/DurableTask.Core.csproj" />
    <ProjectReference Include="src/DurableTask.Emulator/DurableTask.Emulator.csproj" />
  </ItemGroup>
</Project>